Repository 2nd-Layer/www.dolcapool.eu, pull requests merged in 2020-10, with the labels that each got.

#20 Re-design Cardano Stake Pool page
  src/frontend/assets/images/logos/dolca-pool-logo-blue-with-transparent-bg.png
  src/frontend/assets/images/logos/dolca-pool-logo-white-with-blue-bg.png
  src/frontend/assets/images/logos/dolca-pool-logo-white-with-transparent-bg.png
  src/frontend/assets/images/logos/logo-header-white.svg
  src/frontend/assets/images/logos/logo-white.svg
  src/frontend/assets/scss/components/_navbar.scss
  src/frontend/assets/scss/core.scss
  src/frontend/components/Navigation/NavBarClone.vue
  src/frontend/components/Navigation/NavBarStatic.vue
  src/frontend/components/footer.vue
  src/frontend/layouts/landing.vue
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/pages/cardano-stake-pool.vue
  src/frontend/pages/index.vue
Labels: UI, content, enhancement

#21 Update Cardano Stake Pool page
  src/frontend/pages/cardano-stake-pool.vue
Labels: UI

#23 Update About Cardano page
  src/frontend/assets/images/icons/ouroboros.svg
  src/frontend/pages/about-cardano.vue
Labels: UI, assets, content

#26 Update live pool stats
  src/frontend/pages/cardano-stake-pool.vue
Labels: UI, enhancement

#27 Update Pool Stats
  src/frontend/pages/cardano-stake-pool.vue
Labels: UI, enhancement

#30 Update index.vue
  src/frontend/pages/index.vue
Labels: UI, enhancement

#38 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement, javascript

#40 Update browser tab title to DOLCA Stake Pool
  src/frontend/layouts/default.vue
  src/frontend/layouts/landing.vue
  src/frontend/nuxt.config.js
Labels: UI, enhancement

#41 Fix CI and update Network Governance description
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/pages/cardano-stake-pool.vue
Labels: bug, content, dependencies, enhancement, javascript

#42 Fix Blockchain Technology link
  src/frontend/pages/cardano-stake-pool.vue
Labels: bug, content

#43 Remove symbol from header logo
  src/frontend/assets/images/logos/logo-header-no-symbol-white.svg
  src/frontend/components/Navigation/NavBarClone.vue
Labels: UI, assets

#44 Remove symbol from header logo
  src/frontend/components/Navigation/NavBarStatic.vue
Labels: UI, bug

#46 Update Cardano Stake Pool page
  src/frontend/pages/cardano-stake-pool.vue
Labels: UI, content, enhancement

#45 Update README.md
  README.md
Labels: documentation

#47 Fix typos on Cardano Stake Pool page
  src/frontend/pages/cardano-stake-pool.vue
Labels: bug, content, enhancement

#48 Fix typos on Cardano Stake Pool page
  src/frontend/pages/cardano-stake-pool.vue
Labels: UI, bug, content, enhancement

#49 Fix: Close nuxt-link tag
  src/frontend/pages/cardano-stake-pool.vue
Labels: UI, bug, content, enhancement

#53 Update About Cardano page
  src/frontend/pages/about-cardano.vue
Labels: content, enhancement

#54 Add DOLCA Pool Metadata
  src/frontend/static/dolca.extended-metadata.json
  src/frontend/static/dolca.metadata.json
Labels: assets, content, enhancement, pool metadata

#56 Fix About Cardano page typography
  src/frontend/pages/about-cardano.vue
Labels: UI, bug, content

#57 Move first CTA to the right...
  src/frontend/pages/about-cardano.vue
Labels: UI, content, enhancement

#58 Fix About Cardano typography
  src/frontend/pages/about-cardano.vue
Labels: UI, bug, content, enhancement

#59 Fix About Cardano typography
  src/frontend/pages/about-cardano.vue
Labels: UI, bug, content, enhancement

#60 Update Accounting model section
  src/frontend/pages/about-cardano.vue
Labels: UI, bug, content, documentation, enhancement

#61 Fix typo & words inside strong element by adding class has-text-white
  src/frontend/pages/about-cardano.vue
Labels: UI, bug, content, documentation

#62 Fix typo
  src/frontend/pages/about-cardano.vue
Labels: bug, content, enhancement

#63 Update Accounting model section
  src/frontend/pages/about-cardano.vue
Labels: UI, bug, content, enhancement

#65 Add The Extended UTXO Model link
  src/frontend/pages/about-cardano.vue
Labels: content, enhancement

#66 Add placeholders for Technical sections
  src/frontend/pages/about-cardano.vue
Labels: UI, content, enhancement, help wanted

#67 Change columns layout of About Cardano science section
  src/frontend/pages/about-cardano.vue
Labels: UI, content, enhancement

#68 Change Technical section logos
  src/frontend/assets/images/icons/hydra.svg
  src/frontend/assets/images/icons/marlowe.svg
  src/frontend/assets/images/icons/plutus.svg
  src/frontend/pages/about-cardano.vue
Labels: UI, assets, content, enhancement

#69 Don't perform CodeQL on push to master
  .github/workflows/codeql-analysis.yml
Labels: DevOps, enhancement

#70 Fix image color
  src/frontend/assets/images/icons/hydra.svg
  src/frontend/assets/images/icons/marlowe.svg
  src/frontend/assets/images/icons/ouroboros.svg
  src/frontend/assets/images/icons/plutus.svg
  src/frontend/pages/about-cardano.vue
Labels: UI, assets, content, enhancement

#71 Revert "Don't perform CodeQL on push to master"
  .github/workflows/codeql-analysis.yml
Labels: DevOps, bug

#73 Change from mode to ssr option in nuxt.config.js
  src/frontend/nuxt.config.js
Labels: enhancement, javascript

#74 Updated README.md with setup development instructions
  README.md
  src/frontend/package-lock.json
Labels: DevOps, documentation, enhancement

#77 Fix for #64
  src/frontend/assets/scss/core.scss
  src/frontend/pages/about-cardano.vue
  src/frontend/pages/index.vue
Labels: UI, content, enhancement

#80 Fix typo in link to Our Team
  src/frontend/pages/cardano-stake-pool.vue
Labels: bug, content, enhancement

#81 Center 404 Error Message
  src/frontend/layouts/error.vue
Labels: UI, bug, content, enhancement

#79 Fetch Carrdano Blockchain parameterss from ADA Pools
  src/frontend/pages/about-cardano.vue
Labels: bug, content, enhancement, help wanted, javascript, work-in-progress

#85 Optimize Images.
  src/frontend/nuxt.config.js
  src/frontend/package-lock.json
  src/frontend/package.json
Labels: UI, content, enhancement

#78 Begin i18n.
  src/frontend/assets/scss/components/_locale-switcher.scss
  src/frontend/assets/scss/core.scss
  src/frontend/components/Navigation/NavContent.vue
  src/frontend/components/footer.vue
  src/frontend/lang/cz-CZ.js
  src/frontend/lang/en-US.js
  src/frontend/layouts/landing.vue
  src/frontend/nuxt.config.js
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/pages/cardano-stake-pool.vue
  src/frontend/pages/index.vue
Labels: UI, enhancement, help wanted, i18n, javascript, work-in-progress

#84 init our team page
  src/frontend/assets/images/our_team/cody_butz.png
  src/frontend/assets/images/our_team/mark_stopka.png
  src/frontend/pages/cardano-stake-pool.vue
  src/frontend/pages/dolca-stake-pool-team.vue
Labels: content, work-in-progress

#86 Add linter.
  .gitattributes
  .github/workflows/deploy-github-pages.yaml
  .github/workflows/test-frontend-build.yaml
  src/.editorconfig
  src/frontend/.eslintrc.js
  src/frontend/components/Navigation/NavBarClone.vue
  src/frontend/components/Navigation/NavBarStatic.vue
  src/frontend/components/Navigation/NavContent.vue
  src/frontend/components/Navigation/ResponsiveToggle.vue
  src/frontend/components/footer.vue
  src/frontend/components/header.vue
  src/frontend/lang/cz-CZ.js
  src/frontend/lang/en-US.js
  src/frontend/layouts/default.vue
  src/frontend/layouts/error.vue
  src/frontend/layouts/landing.vue
  src/frontend/nuxt.config.js
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/pages/about-cardano.vue
  src/frontend/pages/begin-staking-now.vue
  src/frontend/pages/better-late-than-never-partnership.vue
  src/frontend/pages/cardano-stake-pool.vue
  src/frontend/pages/dolca-stake-pool-team.vue
  src/frontend/pages/index.vue
  src/frontend/pages/tezos-bakery.vue
  src/frontend/plugins/particles.js
  src/frontend/store/modals.js
  src/frontend/store/responsive-toggle.js
Labels: DevOps, documentation, enhancement, help wanted, javascript

#93 eslint improvements
  src/frontend/layouts/error.vue
Labels: enhancement

#95 Move to vue/max-len eslint plug-in
  src/frontend/.eslintrc.js
Labels: DevOps, enhancement, javascript

#96 Update README.md
  README.md
Labels: documentation, enhancement

#97 Add DOLCA Stake Pool Technology page
  src/frontend/assets/images/schemas/dolca-pool-topology.svg
  src/frontend/assets/images/schemas/dolca-pool-topology.vsdx
  src/frontend/components/Navigation/NavContent.vue
  src/frontend/lang/en-US.js
  src/frontend/pages/dolca-stake-pool-technology.vue
Labels: DevOps, UI, assets, content, documentation, enhancement, i18n

#98 Update content
  src/frontend/components/Navigation/NavContent.vue
  src/frontend/components/footer.vue
  src/frontend/pages/about-cardano.vue
  src/frontend/pages/dolca-stake-pool-technology.vue
Labels: UI, content, documentation, enhancement

#99 Update footer
  src/frontend/components/footer.vue
  src/frontend/pages/about-cardano.vue
Labels: UI, business/marketing, content, enhancement

#100 Update footer
  src/frontend/components/footer.vue
Labels: UI, business/marketing, content, enhancement

#104 Add Our Partners section
  src/frontend/components/Navigation/NavContent.vue
  src/frontend/lang/en-US.js
  src/frontend/pages/our-partners/better-late-than-never-partnership.vue
  src/frontend/pages/our-partners/index.vue
Labels: UI, business/marketing, content, enhancement

#107 Update Cardano Stake Pool page
  src/frontend/lang/en-US.js
  src/frontend/pages/cardano-stake-pool.vue
  src/frontend/pages/dolca-stake-pool-team.vue
Labels: UI, content, enhancement

#108 Fix duplicate words
  src/frontend/pages/cardano-stake-pool.vue
Labels: enhancement, i18n

#113 ci: Ensure your PR title matches the Conventional Commits spec
  .github/workflows/check-pr-title.yaml
Labels: DevOps, enhancement

#115 ci: Define lint job name
  .github/workflows/check-pr-title.yaml
Labels: DevOps, enhancement

#114 docs: Add section about pull requests
  README.md
Labels: documentation, enhancement

#116 fix: Typo in README.md
  README.md
Labels: documentation

#117 fix(docs): Typo
  README.md
Labels: documentation, enhancement, i18n
